### **Edward Bayogos BSIS-3A**
#**IS 110**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
%cd /content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos

/content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos


In [8]:
!pwd

/content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos


#**EXERCISE A**

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [9]:
import numpy as np

In [10]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [11]:
print("Shape of A:", A.shape)

Shape of A: (2, 3)


In [12]:
print("Max value using method:", A.max())

Max value using method: 60


In [13]:
print("Max value using np function:", np.max(A))

Max value using np function: 60


#**EXERCISE B**

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [14]:
B = np.ones((5, 5), dtype=int)

In [15]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
print("Shape:", B.shape)

Shape: (5, 5)


In [17]:
print("Size:", B.size)

Size: 25


In [18]:
print("Dimensions:", B.ndim)

Dimensions: 2


#**EXERCISE C**

In [20]:
C = np.arange(-5, 6)

In [21]:
result = C * 2

In [22]:
print("Original Array:", C)

Original Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [23]:
print("Resulting Array:", result)

Resulting Array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


#**PUSH in PythonEnvi_Bayogos and GIT**

In [24]:
!find /content/drive/MyDrive -name "NumPyExercise.ipynb"

/content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos/PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb


In [25]:
!git config --global user.email "edward.bayogos@students.isatu.edu.ph"
!git config --global user.name "Edward Bayogos"

In [45]:
!ls "PythonEnvi_Bayogos/CHAPTERS_BAYOGOS"

Chapter2.ipynb	Chapter4.ipynb	NumPyExercise.ipynb
Chapter3.ipynb	Chapter5.ipynb


In [40]:
!git add "PythonEnvi_Bayogos/CHAPTERS_BAYOGOS"

In [46]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos/.git/


In [33]:
!git status

Refresh index: 100% (5136/5136), done.
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/Chapter2.ipynb
	new file:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/Chapter3.ipynb
	new file:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/Chapter4.ipynb
	new file:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/Chapter5.ipynb
	new file:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter 2.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter _3.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter_

In [47]:
!git commit -m "Add CHAPTERS_BAYOGOS"

On branch main
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter 2.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter _3.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter_4.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter_5.ipynb
	deleted:    PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/NumPyExercises.ipynb
	modified:   PythonEnvi_Bayogos/myenv/bin/python
	modified:   PythonEnvi_Bayogos/myenv/bin/python3
	modified:   PythonEnvi_Bayogos/myenv/bin/python3.12

no changes added to commit (use "git add" and/or "git commit -a")


In [52]:
!git add .
!git commit -m "Final update before submission"

[main bd063b7] Final update before submission
 6 files changed, 1 insertion(+), 6 deletions(-)
 delete mode 100644 PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter 2.ipynb
 delete mode 100644 PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter _3.ipynb
 delete mode 100644 PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter_4.ipynb
 delete mode 100644 PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/Chapter_5.ipynb
 delete mode 100644 PythonEnvi_Bayogos/myenv/CHAPTERS_BAYOGOS/NumPyExercises.ipynb


In [53]:
!git status

Refresh index: 100% (5131/5131), done.
On branch main
Your branch is ahead of 'origin/main' by 4 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb
	modified:   PythonEnvi_Bayogos/myenv/bin/python
	modified:   PythonEnvi_Bayogos/myenv/bin/python3
	modified:   PythonEnvi_Bayogos/myenv/bin/python3.12

no changes added to commit (use "git add" and/or "git commit -a")


In [54]:
!pwd

/content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos


In [55]:
!git rev-parse --show-toplevel

/content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos


In [67]:
!git remote -v

origin	https://github.com/edwardbayogos-13/IS110_repo_Bayogos.git (fetch)
origin	https://github.com/edwardbayogos-13/IS110_repo_Bayogos.git (push)


In [66]:
!git remote set-url origin https://github.com/edwardbayogos-13/IS110_repo_Bayogos.git

In [60]:
!git status -s

Refresh index: 100% (5131/5131), done.
 M PythonEnvi_Bayogos/CHAPTERS_BAYOGOS/NumPyExercise.ipynb
 M PythonEnvi_Bayogos/myenv/bin/python
 M PythonEnvi_Bayogos/myenv/bin/python3
 M PythonEnvi_Bayogos/myenv/bin/python3.12


In [74]:
import os

# Ensure you are in the correct directory if needed, though it seems you already are
# %cd /content/drive/MyDrive/ColabNotebooks/IS110_BPerformance_Bayogos/IS110_repo_Bayogos

!git stash push -m "Temporary stash before pull --rebase"
!git pull origin main --rebase
!git stash pop

[main f1dc98b] Committing local changes before pulling from remote
 1 file changed, 1 insertion(+), 1 deletion(-)
[main 8692bb1] Committing remaining local changes
 1 file changed, 1 insertion(+), 1 deletion(-)
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.


In [71]:
!git pull origin main --rebase

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.


In [69]:
!git push origin main --force

fatal: could not read Username for 'https://github.com': No such device or address


In [70]:
!git push https://edwardbayogos-13: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@github.com/edwardbayogos-13/IS110_repo_Bayogos.git main

To https://github.com/edwardbayogos-13/IS110_repo_Bayogos.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/edwardbayogos-13/IS110_repo_Bayogos.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
